#%RAML 1.0 DataType
type: object
properties:
  Name: 
    type: string
  age: 
    type: string
  mobile:  
    type: string
  company: 
    type: string
  address: 
    type: string         
   


  

  
  

    
       